path: /home/jphillips/fearnworks/mtg_pipeline/example_dataset # update for your location
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: collector_number
  1: set